// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna3_5/ldsdir.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna3_5 {

LdsParamLoadLdsdir::LdsParamLoadLdsdir(const MachineInst *inst)
    : Ldsdir("lds_param_load", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<LdsParamLoadLdsdir>()),
      vdst(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdst),
      attr(32, OperandType::OPR_ATTR, reinterpret_cast<const OpEncoding *>(inst)->attr) {
  dst_operands_[0] = &vdst;
  src_operands_[0] = &attr;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
}

void LdsParamLoadLdsdir::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  (void)wf; // Interpolation/LDS-direct: no-op in compute simulation.
}

LdsDirectLoadLdsdir::LdsDirectLoadLdsdir(const MachineInst *inst)
    : Ldsdir("lds_direct_load", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<LdsDirectLoadLdsdir>()),
      vdst(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdst) {
  dst_operands_[0] = &vdst;
  state_.num_src_operands = 0;
  state_.num_dst_operands = 1;
}

void LdsDirectLoadLdsdir::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  (void)wf; // Interpolation/LDS-direct: no-op in compute simulation.
}

} // namespace rdna3_5
} // namespace rocjitsu
