// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna3_5/sop1.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include "util/log.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <format>
#include <limits>

namespace rocjitsu {
namespace rdna3_5 {

SMovB32Sop1::SMovB32Sop1(const MachineInst *inst)
    : Sop1("s_mov_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMovB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  sdst.write_scalar(wf, ssrc0.read_scalar(wf));
}

SMovB64Sop1::SMovB64Sop1(const MachineInst *inst)
    : Sop1("s_mov_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMovB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  sdst.write_scalar64(wf, ssrc0.read_scalar64(wf));
}

SCmovB32Sop1::SCmovB32Sop1(const MachineInst *inst)
    : Sop1("s_cmov_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmovB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  state_.flags |= PREDICATED_DEF;
}

void SCmovB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  if (wf.read_scc())
    sdst.write_scalar(wf, ssrc0.read_scalar(wf));
}

SCmovB64Sop1::SCmovB64Sop1(const MachineInst *inst)
    : Sop1("s_cmov_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmovB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  state_.flags |= PREDICATED_DEF;
}

void SCmovB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  if (wf.read_scc())
    sdst.write_scalar64(wf, ssrc0.read_scalar64(wf));
}

SBrevB32Sop1::SBrevB32Sop1(const MachineInst *inst)
    : Sop1("s_brev_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBrevB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBrevB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = 0;
  for (int i = 0; i < 32; ++i)
    result |= ((val >> i) & 1) << (31 - i);
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SBrevB64Sop1::SBrevB64Sop1(const MachineInst *inst)
    : Sop1("s_brev_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBrevB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBrevB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint64_t result = 0;
  for (int i = 0; i < 64; ++i)
    result |= ((val >> i) & 1) << (63 - i);
  sdst.write_scalar64(wf, result);
  wf.write_scc(result != 0);
}

SCtzI32B32Sop1::SCtzI32B32Sop1(const MachineInst *inst)
    : Sop1("s_ctz_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCtzI32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCtzI32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result =
      val == 0 ? static_cast<uint32_t>(-1) : static_cast<uint32_t>(std::countr_zero(val));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCtzI32B64Sop1::SCtzI32B64Sop1(const MachineInst *inst)
    : Sop1("s_ctz_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCtzI32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCtzI32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint32_t result =
      val == 0 ? static_cast<uint32_t>(-1) : static_cast<uint32_t>(std::countr_zero(val));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SClzI32U32Sop1::SClzI32U32Sop1(const MachineInst *inst)
    : Sop1("s_clz_i32_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SClzI32U32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SClzI32U32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result =
      val == 0 ? static_cast<uint32_t>(-1) : static_cast<uint32_t>(std::countl_zero(val));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SClzI32U64Sop1::SClzI32U64Sop1(const MachineInst *inst)
    : Sop1("s_clz_i32_u64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SClzI32U64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SClzI32U64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint32_t result =
      val == 0 ? static_cast<uint32_t>(-1) : static_cast<uint32_t>(std::countl_zero(val));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SClsI32Sop1::SClsI32Sop1(const MachineInst *inst)
    : Sop1("s_cls_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SClsI32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SClsI32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  int32_t sval = static_cast<int32_t>(val);
  uint32_t uval = sval < 0 ? ~static_cast<uint32_t>(sval) : static_cast<uint32_t>(sval);
  uint32_t result = uval == 0 ? 31u : static_cast<uint32_t>(std::countl_zero(uval)) - 1;
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SClsI32I64Sop1::SClsI32I64Sop1(const MachineInst *inst)
    : Sop1("s_cls_i32_i64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SClsI32I64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SClsI32I64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int64_t sval = static_cast<int64_t>(ssrc0.read_scalar64(wf));
  uint64_t uval = sval < 0 ? ~static_cast<uint64_t>(sval) : static_cast<uint64_t>(sval);
  uint32_t result = uval == 0 ? 63u : static_cast<uint32_t>(std::countl_zero(uval)) - 1;
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SSextI32I8Sop1::SSextI32I8Sop1(const MachineInst *inst)
    : Sop1("s_sext_i32_i8", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSextI32I8Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SSextI32I8Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = static_cast<uint32_t>(static_cast<int32_t>(static_cast<int8_t>(val & 0xFF)));
  sdst.write_scalar(wf, result);
}

SSextI32I16Sop1::SSextI32I16Sop1(const MachineInst *inst)
    : Sop1("s_sext_i32_i16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSextI32I16Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SSextI32I16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = static_cast<uint32_t>(static_cast<int32_t>(static_cast<int16_t>(val & 0xFFFF)));
  sdst.write_scalar(wf, result);
}

SBitset0B32Sop1::SBitset0B32Sop1(const MachineInst *inst)
    : Sop1("s_bitset0_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset0B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset0B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t bit = ssrc0.read_scalar(wf);
  uint32_t result = sdst.read_scalar(wf) & ~(1u << (bit & 31));
  sdst.write_scalar(wf, result);
}

SBitset0B64Sop1::SBitset0B64Sop1(const MachineInst *inst)
    : Sop1("s_bitset0_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset0B64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset0B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t bit = ssrc0.read_scalar(wf);
  uint64_t result = sdst.read_scalar64(wf) & ~(1ULL << (bit & 63));
  sdst.write_scalar64(wf, result);
}

SBitset1B32Sop1::SBitset1B32Sop1(const MachineInst *inst)
    : Sop1("s_bitset1_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset1B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset1B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t bit = ssrc0.read_scalar(wf);
  uint32_t result = sdst.read_scalar(wf) | (1u << (bit & 31));
  sdst.write_scalar(wf, result);
}

SBitset1B64Sop1::SBitset1B64Sop1(const MachineInst *inst)
    : Sop1("s_bitset1_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitset1B64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &ssrc0;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitset1B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t bit = ssrc0.read_scalar(wf);
  uint64_t result = sdst.read_scalar64(wf) | (1ULL << (bit & 63));
  sdst.write_scalar64(wf, result);
}

SBitreplicateB64B32Sop1::SBitreplicateB64B32Sop1(const MachineInst *inst)
    : Sop1("s_bitreplicate_b64_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitreplicateB64B32Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBitreplicateB64B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SAbsI32Sop1::SAbsI32Sop1(const MachineInst *inst)
    : Sop1("s_abs_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAbsI32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAbsI32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t val = static_cast<int32_t>(ssrc0.read_scalar(wf));
  uint32_t uval = static_cast<uint32_t>(val);
  uint32_t result = val < 0 ? (0u - uval) : uval;
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SBcnt0I32B32Sop1::SBcnt0I32B32Sop1(const MachineInst *inst)
    : Sop1("s_bcnt0_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt0I32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt0I32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = static_cast<uint32_t>(std::popcount(~val));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SBcnt0I32B64Sop1::SBcnt0I32B64Sop1(const MachineInst *inst)
    : Sop1("s_bcnt0_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt0I32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt0I32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint64_t result = static_cast<uint64_t>(std::popcount(~val));
  sdst.write_scalar64(wf, result);
  wf.write_scc(result != 0);
}

SBcnt1I32B32Sop1::SBcnt1I32B32Sop1(const MachineInst *inst)
    : Sop1("s_bcnt1_i32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt1I32B32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt1I32B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = static_cast<uint32_t>(std::popcount(val));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SBcnt1I32B64Sop1::SBcnt1I32B64Sop1(const MachineInst *inst)
    : Sop1("s_bcnt1_i32_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBcnt1I32B64Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SBcnt1I32B64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint64_t result = static_cast<uint64_t>(std::popcount(val));
  sdst.write_scalar64(wf, result);
  wf.write_scc(result != 0);
}

SQuadmaskB32Sop1::SQuadmaskB32Sop1(const MachineInst *inst)
    : Sop1("s_quadmask_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SQuadmaskB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SQuadmaskB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = 0;
  for (int q = 0; q < 8; ++q)
    if (val & (0xFu << (q * 4)))
      result |= (1u << q);
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SQuadmaskB64Sop1::SQuadmaskB64Sop1(const MachineInst *inst)
    : Sop1("s_quadmask_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SQuadmaskB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SQuadmaskB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint64_t result = 0;
  for (int q = 0; q < 16; ++q)
    if (val & (0xFULL << (q * 4)))
      result |= (1ULL << q);
  sdst.write_scalar64(wf, result);
  wf.write_scc(result != 0);
}

SWqmB32Sop1::SWqmB32Sop1(const MachineInst *inst)
    : Sop1("s_wqm_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SWqmB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SWqmB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = 0;
  for (int q = 0; q < 8; ++q)
    if (val & (0xFu << (q * 4)))
      result |= (0xFu << (q * 4));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SWqmB64Sop1::SWqmB64Sop1(const MachineInst *inst)
    : Sop1("s_wqm_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SWqmB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SWqmB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint64_t result = 0;
  for (int q = 0; q < 16; ++q)
    if (val & (0xFULL << (q * 4)))
      result |= (0xFULL << (q * 4));
  sdst.write_scalar64(wf, result);
  wf.write_scc(result != 0);
}

SNotB32Sop1::SNotB32Sop1(const MachineInst *inst)
    : Sop1("s_not_b32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNotB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNotB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = ~val;
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SNotB64Sop1::SNotB64Sop1(const MachineInst *inst)
    : Sop1("s_not_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNotB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNotB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t val = ssrc0.read_scalar64(wf);
  uint64_t result = ~val;
  sdst.write_scalar64(wf, result);
  wf.write_scc(result != 0);
}

SAndSaveexecB32Sop1::SAndSaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_and_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndSaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndSaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec & src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SAndSaveexecB64Sop1::SAndSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_and_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec & src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SOrSaveexecB32Sop1::SOrSaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_or_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrSaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrSaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec | src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SOrSaveexecB64Sop1::SOrSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_or_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec | src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SXorSaveexecB32Sop1::SXorSaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_xor_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SXorSaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SXorSaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec ^ src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SXorSaveexecB64Sop1::SXorSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_xor_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SXorSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SXorSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec ^ src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SNandSaveexecB32Sop1::SNandSaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_nand_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SNandSaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNandSaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~(old_exec & src);
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SNandSaveexecB64Sop1::SNandSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_nand_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SNandSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNandSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~(old_exec & src);
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SNorSaveexecB32Sop1::SNorSaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_nor_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SNorSaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNorSaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~(old_exec | src);
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SNorSaveexecB64Sop1::SNorSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_nor_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SNorSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SNorSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~(old_exec | src);
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SXnorSaveexecB32Sop1::SXnorSaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_xnor_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SXnorSaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SXnorSaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~(old_exec ^ src);
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SXnorSaveexecB64Sop1::SXnorSaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_xnor_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SXnorSaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SXnorSaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~(old_exec ^ src);
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SAndNot0SaveexecB32Sop1::SAndNot0SaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_and_not0_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot0SaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot0SaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec & ~src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SAndNot0SaveexecB64Sop1::SAndNot0SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_and_not0_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot0SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot0SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec & ~src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SOrNot0SaveexecB32Sop1::SOrNot0SaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_or_not0_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrNot0SaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrNot0SaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec | ~src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SOrNot0SaveexecB64Sop1::SOrNot0SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_or_not0_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrNot0SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrNot0SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = old_exec | ~src;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SAndNot1SaveexecB32Sop1::SAndNot1SaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_and_not1_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot1SaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot1SaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~src & ~old_exec;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SAndNot1SaveexecB64Sop1::SAndNot1SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_and_not1_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot1SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot1SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~src & ~old_exec;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SOrNot1SaveexecB32Sop1::SOrNot1SaveexecB32Sop1(const MachineInst *inst)
    : Sop1("s_or_not1_saveexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrNot1SaveexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrNot1SaveexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~src | old_exec;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SOrNot1SaveexecB64Sop1::SOrNot1SaveexecB64Sop1(const MachineInst *inst)
    : Sop1("s_or_not1_saveexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SOrNot1SaveexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SOrNot1SaveexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t old_exec = wf.exec();
  uint64_t src = ssrc0.read_scalar64(wf);
  sdst.write_scalar64(wf, old_exec);
  uint64_t result = ~src | old_exec;
  util::Logger::vm([&](auto &os) {
    os << std::format("saveexec ssrc0_ev={} src={:#x} exec={:#x}->{:#x}", ssrc0.encoding_value(),
                      src, old_exec, result);
  });
  wf.set_exec(result);
  wf.write_scc(result != 0);
}

SAndNot0WrexecB32Sop1::SAndNot0WrexecB32Sop1(const MachineInst *inst)
    : Sop1("s_and_not0_wrexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot0WrexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot0WrexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t src = ssrc0.read_scalar64(wf);
  wf.set_exec(wf.exec() & ~src);
}

SAndNot0WrexecB64Sop1::SAndNot0WrexecB64Sop1(const MachineInst *inst)
    : Sop1("s_and_not0_wrexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot0WrexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot0WrexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t src = ssrc0.read_scalar64(wf);
  wf.set_exec(wf.exec() & ~src);
}

SAndNot1WrexecB32Sop1::SAndNot1WrexecB32Sop1(const MachineInst *inst)
    : Sop1("s_and_not1_wrexec_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot1WrexecB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot1WrexecB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t src = ssrc0.read_scalar64(wf);
  wf.set_exec(src & ~wf.exec());
}

SAndNot1WrexecB64Sop1::SAndNot1WrexecB64Sop1(const MachineInst *inst)
    : Sop1("s_and_not1_wrexec_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SAndNot1WrexecB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SAndNot1WrexecB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t src = ssrc0.read_scalar64(wf);
  wf.set_exec(src & ~wf.exec());
}

SMovrelsB32Sop1::SMovrelsB32Sop1(const MachineInst *inst)
    : Sop1("s_movrels_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovrelsB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovrelsB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMovrelsB64Sop1::SMovrelsB64Sop1(const MachineInst *inst)
    : Sop1("s_movrels_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovrelsB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovrelsB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMovreldB32Sop1::SMovreldB32Sop1(const MachineInst *inst)
    : Sop1("s_movreld_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovreldB32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovreldB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMovreldB64Sop1::SMovreldB64Sop1(const MachineInst *inst)
    : Sop1("s_movreld_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovreldB64Sop1>()),
      sdst(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovreldB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SMovrelsd2B32Sop1::SMovrelsd2B32Sop1(const MachineInst *inst)
    : Sop1("s_movrelsd_2_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SMovrelsd2B32Sop1>()),
      sdst(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SMovrelsd2B32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SGetpcB64Sop1::SGetpcB64Sop1(const MachineInst *inst)
    : Sop1("s_getpc_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SGetpcB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst) {
  dst_operands_[0] = &sdst;
  state_.num_src_operands = 0;
  state_.num_dst_operands = 1;
}

void SGetpcB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  sdst.write_scalar64(wf, wf.pc + state_.size_bytes);
}

SSetpcB64Sop1::SSetpcB64Sop1(const MachineInst *inst)
    : Sop1("s_setpc_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetpcB64Sop1>()),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  state_.flags |= INDIRECT_BRANCH;
}

void SSetpcB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  wf.pc = ssrc0.read_scalar64(wf) - state_.size_bytes;
}

SSwappcB64Sop1::SSwappcB64Sop1(const MachineInst *inst)
    : Sop1("s_swappc_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSwappcB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
  state_.flags |= INDIRECT_CALL;
}

void SSwappcB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint64_t next_pc = wf.pc + state_.size_bytes;
  wf.pc = ssrc0.read_scalar64(wf) - state_.size_bytes;
  sdst.write_scalar64(wf, next_pc);
}

SRfeB64Sop1::SRfeB64Sop1(const MachineInst *inst)
    : Sop1("s_rfe_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SRfeB64Sop1>()),
      ssrc0(64, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SRfeB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  (void)wf;
}

SSendmsgRtnB32Sop1::SSendmsgRtnB32Sop1(const MachineInst *inst)
    : Sop1("s_sendmsg_rtn_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSendmsgRtnB32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SENDMSG_RTN, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SSendmsgRtnB32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SSendmsgRtnB64Sop1::SSendmsgRtnB64Sop1(const MachineInst *inst)
    : Sop1("s_sendmsg_rtn_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSendmsgRtnB64Sop1>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SENDMSG_RTN, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SSendmsgRtnB64Sop1::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SCeilF32Sop1::SCeilF32Sop1(const MachineInst *inst)
    : Sop1("s_ceil_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCeilF32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCeilF32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = std::bit_cast<uint32_t>(std::ceil(std::bit_cast<float>(val)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SFloorF32Sop1::SFloorF32Sop1(const MachineInst *inst)
    : Sop1("s_floor_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFloorF32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFloorF32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = std::bit_cast<uint32_t>(std::floor(std::bit_cast<float>(val)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

STruncF32Sop1::STruncF32Sop1(const MachineInst *inst)
    : Sop1("s_trunc_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<STruncF32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void STruncF32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = std::bit_cast<uint32_t>(std::trunc(std::bit_cast<float>(val)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SRndneF32Sop1::SRndneF32Sop1(const MachineInst *inst)
    : Sop1("s_rndne_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SRndneF32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SRndneF32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = std::bit_cast<uint32_t>(std::nearbyint(std::bit_cast<float>(val)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCvtF32I32Sop1::SCvtF32I32Sop1(const MachineInst *inst)
    : Sop1("s_cvt_f32_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtF32I32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtF32I32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = std::bit_cast<uint32_t>(static_cast<float>(static_cast<int32_t>(val)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCvtF32U32Sop1::SCvtF32U32Sop1(const MachineInst *inst)
    : Sop1("s_cvt_f32_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtF32U32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtF32U32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = std::bit_cast<uint32_t>(static_cast<float>(val));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCvtI32F32Sop1::SCvtI32F32Sop1(const MachineInst *inst)
    : Sop1("s_cvt_i32_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtI32F32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtI32F32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  float f = std::bit_cast<float>(val);
  int32_t r = std::isnan(f) ? 0
                            : (f >= 2147483648.0f
                                   ? INT32_MAX
                                   : (f < -2147483648.0f ? INT32_MIN : static_cast<int32_t>(f)));
  uint32_t result = static_cast<uint32_t>(r);
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCvtU32F32Sop1::SCvtU32F32Sop1(const MachineInst *inst)
    : Sop1("s_cvt_u32_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtU32F32Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtU32F32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  float f = std::bit_cast<float>(val);
  uint32_t result = (std::isnan(f) || f < 0.0f)
                        ? 0u
                        : (f >= 4294967296.0f ? UINT32_MAX : static_cast<uint32_t>(f));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCvtF16F32Sop1::SCvtF16F32Sop1(const MachineInst *inst)
    : Sop1("s_cvt_f16_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtF16F32Sop1>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtF16F32Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = static_cast<uint32_t>(util::f32_to_f16(std::bit_cast<float>(val)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCvtF32F16Sop1::SCvtF32F16Sop1(const MachineInst *inst)
    : Sop1("s_cvt_f32_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtF32F16Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtF32F16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result = std::bit_cast<uint32_t>(util::f16_to_f32(static_cast<uint16_t>(val & 0xFFFF)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCvtHiF32F16Sop1::SCvtHiF32F16Sop1(const MachineInst *inst)
    : Sop1("s_cvt_hi_f32_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCvtHiF32F16Sop1>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCvtHiF32F16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t result =
      std::bit_cast<uint32_t>(util::f16_to_f32(static_cast<uint16_t>((val >> 16) & 0xFFFF)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SCeilF16Sop1::SCeilF16Sop1(const MachineInst *inst)
    : Sop1("s_ceil_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCeilF16Sop1>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SCeilF16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  float f = util::f16_to_f32(static_cast<uint16_t>(val & 0xFFFF));
  uint32_t result = static_cast<uint32_t>(util::f32_to_f16(std::ceil(f)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SFloorF16Sop1::SFloorF16Sop1(const MachineInst *inst)
    : Sop1("s_floor_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SFloorF16Sop1>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SFloorF16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  float f = util::f16_to_f32(static_cast<uint16_t>(val & 0xFFFF));
  uint32_t result = static_cast<uint32_t>(util::f32_to_f16(std::floor(f)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

STruncF16Sop1::STruncF16Sop1(const MachineInst *inst)
    : Sop1("s_trunc_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<STruncF16Sop1>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void STruncF16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  float f = util::f16_to_f32(static_cast<uint16_t>(val & 0xFFFF));
  uint32_t result = static_cast<uint32_t>(util::f32_to_f16(std::trunc(f)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

SRndneF16Sop1::SRndneF16Sop1(const MachineInst *inst)
    : Sop1("s_rndne_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SRndneF16Sop1>()),
      sdst(16, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &ssrc0;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const Sop1InstLiteralMachineInst *>(inst)->simm32));
}

void SRndneF16Sop1::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t val = ssrc0.read_scalar(wf);
  float f = util::f16_to_f32(static_cast<uint16_t>(val & 0xFFFF));
  uint32_t result = static_cast<uint32_t>(util::f32_to_f16(std::nearbyint(f)));
  sdst.write_scalar(wf, result);
  wf.write_scc(result != 0);
}

} // namespace rdna3_5
} // namespace rocjitsu
