// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna3_5/sopk.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include "util/log.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna3_5 {

SMovkI32Sopk::SMovkI32Sopk(const MachineInst *inst)
    : Sopk("s_movk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMovkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
}

void SMovkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  sdst.write_scalar(wf, static_cast<uint32_t>(static_cast<int32_t>(
                            static_cast<int16_t>(simm16.state_.encoding_value))));
}

SVersionSopk::SVersionSopk(const MachineInst *inst)
    : Sopk("s_version", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SVersionSopk>()),
      simm16(16, OperandType::OPR_VERSION, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 0;
}

void SVersionSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SCmovkI32Sopk::SCmovkI32Sopk(const MachineInst *inst)
    : Sopk("s_cmovk_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmovkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
  state_.flags |= PREDICATED_DEF;
}

void SCmovkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  if (wf.read_scc())
    sdst.write_scalar(wf, static_cast<uint32_t>(static_cast<int32_t>(
                              static_cast<int16_t>(simm16.state_.encoding_value))));
}

SCmpkEqI32Sopk::SCmpkEqI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_eq_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkEqI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkEqI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  wf.write_scc(s0 == imm);
}

SCmpkLgI32Sopk::SCmpkLgI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lg_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLgI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkLgI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  wf.write_scc(s0 != imm);
}

SCmpkGtI32Sopk::SCmpkGtI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_gt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGtI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkGtI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  wf.write_scc(s0 > imm);
}

SCmpkGeI32Sopk::SCmpkGeI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_ge_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGeI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkGeI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  wf.write_scc(s0 >= imm);
}

SCmpkLtI32Sopk::SCmpkLtI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLtI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkLtI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  wf.write_scc(s0 < imm);
}

SCmpkLeI32Sopk::SCmpkLeI32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_le_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLeI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkLeI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  wf.write_scc(s0 <= imm);
}

SCmpkEqU32Sopk::SCmpkEqU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_eq_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkEqU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkEqU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t s0 = sdst.read_scalar(wf);
  uint32_t imm = static_cast<uint32_t>(static_cast<uint16_t>(simm16.state_.encoding_value));
  wf.write_scc(s0 == imm);
}

SCmpkLgU32Sopk::SCmpkLgU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lg_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLgU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkLgU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t s0 = sdst.read_scalar(wf);
  uint32_t imm = static_cast<uint32_t>(static_cast<uint16_t>(simm16.state_.encoding_value));
  wf.write_scc(s0 != imm);
}

SCmpkGtU32Sopk::SCmpkGtU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_gt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGtU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkGtU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t s0 = sdst.read_scalar(wf);
  uint32_t imm = static_cast<uint32_t>(static_cast<uint16_t>(simm16.state_.encoding_value));
  wf.write_scc(s0 > imm);
}

SCmpkGeU32Sopk::SCmpkGeU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_ge_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkGeU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkGeU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t s0 = sdst.read_scalar(wf);
  uint32_t imm = static_cast<uint32_t>(static_cast<uint16_t>(simm16.state_.encoding_value));
  wf.write_scc(s0 >= imm);
}

SCmpkLtU32Sopk::SCmpkLtU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_lt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLtU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkLtU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t s0 = sdst.read_scalar(wf);
  uint32_t imm = static_cast<uint32_t>(static_cast<uint16_t>(simm16.state_.encoding_value));
  wf.write_scc(s0 < imm);
}

SCmpkLeU32Sopk::SCmpkLeU32Sopk(const MachineInst *inst)
    : Sopk("s_cmpk_le_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpkLeU32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
}

void SCmpkLeU32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint32_t s0 = sdst.read_scalar(wf);
  uint32_t imm = static_cast<uint32_t>(static_cast<uint16_t>(simm16.state_.encoding_value));
  wf.write_scc(s0 <= imm);
}

SAddkI32Sopk::SAddkI32Sopk(const MachineInst *inst)
    : Sopk("s_addk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SAddkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
}

void SAddkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  int64_t wide = static_cast<int64_t>(s0) + static_cast<int64_t>(imm);
  int32_t result = static_cast<int32_t>(wide);
  sdst.write_scalar(wf, static_cast<uint32_t>(result));
  wf.write_scc(wide != static_cast<int64_t>(result));
}

SMulkI32Sopk::SMulkI32Sopk(const MachineInst *inst)
    : Sopk("s_mulk_i32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SMulkI32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  dst_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 1;
}

void SMulkI32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  int32_t s0 = static_cast<int32_t>(sdst.read_scalar(wf));
  int32_t imm = static_cast<int16_t>(simm16.state_.encoding_value);
  sdst.write_scalar(wf, static_cast<uint32_t>(s0 * imm));
}

SGetregB32Sopk::SGetregB32Sopk(const MachineInst *inst)
    : Sopk("s_getreg_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SGetregB32Sopk>()),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
}

void SGetregB32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint16_t hwreg = simm16.state_.encoding_value;
  uint32_t reg_id = hwreg & 0x3Fu;
  uint32_t offset = (hwreg >> 6) & 0x1Fu;
  uint32_t size = ((hwreg >> 11) & 0x1Fu) + 1;
  uint32_t reg_val = 0;
  switch (reg_id) {
  case 1:
    reg_val = wf.status_raw();
    break;
  case 4:
    reg_val = static_cast<uint32_t>(wf.cu().id());
    break;
  case 5:
    reg_val = static_cast<uint32_t>(wf.cu().id() >> 16);
    break;
  case 6:
    reg_val = (wf.sgpr_alloc().count & 0xFFu) | ((wf.sgpr_alloc().base & 0xFFu) << 8);
    break;
  case 7:
    reg_val = (wf.vgpr_alloc().count & 0xFFu) | ((wf.vgpr_alloc().base & 0xFFu) << 8);
    break;
  default:
    util::Logger::warn("s_getreg_b32: unhandled hwreg id=", reg_id);
    break;
  }
  if (offset + size > 32)
    size = 32 - offset;
  uint32_t mask = (size == 32) ? 0xFFFFFFFFu : ((1u << size) - 1u);
  sdst.write_scalar(wf, (reg_val >> offset) & mask);
}

SSetregB32Sopk::SSetregB32Sopk(const MachineInst *inst)
    : Sopk("s_setreg_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetregB32Sopk>()),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16),
      sdst(32, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst) {
  dst_operands_[0] = &simm16;
  src_operands_[0] = &sdst;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
}

void SSetregB32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint16_t hwreg = simm16.state_.encoding_value;
  uint32_t reg_id = hwreg & 0x3Fu;
  uint32_t offset = (hwreg >> 6) & 0x1Fu;
  uint32_t size = ((hwreg >> 11) & 0x1Fu) + 1;
  if (offset + size > 32)
    size = 32 - offset;
  uint32_t mask = (size == 32) ? 0xFFFFFFFFu : ((1u << size) - 1u);
  uint32_t src = sdst.read_scalar(wf);
  switch (reg_id) {
  case 1: {
    uint32_t s = wf.status_raw();
    s = (s & ~(mask << offset)) | ((src & mask) << offset);
    wf.set_status_raw(s);
    break;
  }
  default:
    util::Logger::warn("s_setreg_b32: unhandled hwreg id=", reg_id);
    break;
  }
}

SSetregImm32B32Sopk::SSetregImm32B32Sopk(const MachineInst *inst)
    : Sopk("s_setreg_imm32_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetregImm32B32Sopk>()),
      simm16(16, OperandType::OPR_HWREG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &simm16;
  state_.num_src_operands = 0;
  state_.num_dst_operands = 1;
}

void SSetregImm32B32Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  uint16_t hwreg = simm16.state_.encoding_value;
  uint32_t reg_id = hwreg & 0x3Fu;
  uint32_t offset = (hwreg >> 6) & 0x1Fu;
  uint32_t size = ((hwreg >> 11) & 0x1Fu) + 1;
  if (offset + size > 32)
    size = 32 - offset;
  uint32_t mask = (size == 32) ? 0xFFFFFFFFu : ((1u << size) - 1u);
  uint32_t src = inst.literal_;
  switch (reg_id) {
  case 1: {
    uint32_t s = wf.status_raw();
    s = (s & ~(mask << offset)) | ((src & mask) << offset);
    wf.set_status_raw(s);
    break;
  }
  default:
    util::Logger::warn("s_setreg_imm32_b32: unhandled hwreg id=", reg_id);
    break;
  }
}

SCallB64Sopk::SCallB64Sopk(const MachineInst *inst)
    : Sopk("s_call_b64", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCallB64Sopk>()),
      sdst(64, OperandType::OPR_SDST, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  dst_operands_[0] = &sdst;
  src_operands_[0] = &simm16;
  state_.num_src_operands = 1;
  state_.num_dst_operands = 1;
  state_.flags |= INDIRECT_CALL;
}

void SCallB64Sopk::execute_impl(amdgpu::Wavefront &wf) {
  [[maybe_unused]] auto &inst = *this;
  sdst.write_scalar64(wf, wf.pc + state_.size_bytes);
  int16_t offset = static_cast<int16_t>(simm16.state_.encoding_value);
  wf.pc = wf.pc + static_cast<int64_t>(offset) * 4 - state_.size_bytes;
}

SWaitcntVscntSopk::SWaitcntVscntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_vscnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntVscntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
  state_.flags |= WAITCNT;
}

void SWaitcntVscntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SWaitcntVmcntSopk::SWaitcntVmcntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_vmcnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntVmcntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
  state_.flags |= WAITCNT;
}

void SWaitcntVmcntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SWaitcntExpcntSopk::SWaitcntExpcntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_expcnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntExpcntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
  state_.flags |= WAITCNT;
}

void SWaitcntExpcntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

SWaitcntLgkmcntSopk::SWaitcntLgkmcntSopk(const MachineInst *inst)
    : Sopk("s_waitcnt_lgkmcnt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntLgkmcntSopk>()),
      sdst(32, OperandType::OPR_SDST_NULL, reinterpret_cast<const OpEncoding *>(inst)->sdst),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &sdst;
  src_operands_[1] = &simm16;
  state_.num_src_operands = 2;
  state_.num_dst_operands = 0;
  state_.flags |= WAITCNT;
}

void SWaitcntLgkmcntSopk::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

} // namespace rdna3_5
} // namespace rocjitsu
