// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

/// @file instruction.h
/// @brief Abstract instruction representation with operands, flags, and dynamic state.

#ifndef ROCJITSU_ISA_INSTRUCTION_H_
#define ROCJITSU_ISA_INSTRUCTION_H_

#include "rocjitsu/isa/operand.h"
#include "util/intrusive_list.h"

#include "rocjitsu/code/rj_code.h"
#include "rocjitsu/vm/rj_vm.h"

#include <array>
#include <cassert>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <utility>

namespace rocjitsu {

/// @brief Instruction property flags.
///
/// @details Enumerator values are pinned to the corresponding
/// @ref rj_code_inst_flag constants so the flags bitmask stored in
/// @ref Instruction::state_.flags matches the emulator plugin ABI.
enum InstFlags : uint64_t {
  /// @brief Unconditional branch.
  BRANCH = ROCJITSU_CODE_INST_FLAG_BRANCH,
  /// @brief Conditional branch.
  COND_BRANCH = ROCJITSU_CODE_INST_FLAG_COND_BRANCH,
  /// @brief Indirect branch (target from register).
  INDIRECT_BRANCH = ROCJITSU_CODE_INST_FLAG_INDIRECT_BRANCH,
  /// @brief Indirect call (target from register, returns to fallthrough).
  INDIRECT_CALL = ROCJITSU_CODE_INST_FLAG_INDIRECT_CALL,
  /// @brief Terminates the program.
  PROGRAM_TERMINATOR = ROCJITSU_CODE_INST_FLAG_PROGRAM_TERMINATOR,
  /// @brief Executes immediately without scheduling latency.
  IMMEDIATELY_EXECUTED = ROCJITSU_CODE_INST_FLAG_IMMEDIATELY_EXECUTED,
  /// @brief Memory operation (load or store).
  MEMORY_OP = ROCJITSU_CODE_INST_FLAG_MEMORY_OP,
  /// @brief Wait-counter instruction (s_waitcnt, s_wait_loadcnt, s_wait_storecnt, etc.).
  WAITCNT = ROCJITSU_CODE_INST_FLAG_WAITCNT,
  /// @brief Barrier instruction (s_barrier, s_barrier_signal, s_barrier_wait).
  BARRIER = ROCJITSU_CODE_INST_FLAG_BARRIER,
  /// @brief Matrix FMA instruction (v_mfma_*, v_smfmac_*).
  MFMA = ROCJITSU_CODE_INST_FLAG_MFMA,
  /// @brief AccVGPR move instruction (v_accvgpr_write, v_accvgpr_read, v_accvgpr_mov).
  ACCVGPR = ROCJITSU_CODE_INST_FLAG_ACCVGPR,
  /// @brief Destination update is conditional and must not kill the old value.
  PREDICATED_DEF = ROCJITSU_CODE_INST_FLAG_PREDICATED_DEF,
};

class BasicBlock;

/// @brief Base class for opaque per-instruction dynamic state.
///
/// @details ISA backends attach subclasses to carry mutable pipeline state (e.g.,
/// computed addresses, response buffers) that lives outside the autogenerated
/// encoding classes. The base class is ISA-neutral.
class DynamicInstState {
public:
  virtual ~DynamicInstState() = default;

  /// @brief Backend-defined tag for pipeline routing or dispatch.
  /// @returns Tag value.
  uint8_t tag() const { return tag_; }

protected:
  uint8_t tag_ = 0;
};

/// @brief Abstract base class that defines the API for an instruction.
class Instruction : public util::IListNode<Instruction, util::IListParent<BasicBlock>> {
public:
  /// @brief Function pointer type for direct (non-virtual) execute dispatch.
  /// @param self The instruction instance.
  /// @param ctx  ISA-specific execution context (cast to concrete type by impl).
  using ExecuteFn = void (*)(Instruction &self, void *ctx);

  /// @brief Construct an instruction with the given mnemonic.
  /// @param[in] mnemonic Human-readable mnemonic (must point to static storage
  ///            or storage that outlives the instruction — typically a string
  ///            literal or a member of the encoding base class).
  Instruction(std::string_view mnemonic, ExecuteFn exec) : execute(exec) {
    state_.mnemonic = mnemonic.data();
  }
  virtual ~Instruction() = default;

  /// @brief Pool allocator hooks, set by the decoder's enable_pool().
  /// Thread-local because each CU partition thread has its own decoder/pool.
  /// Instructions are wholly owned by their CU and always allocated/freed
  /// on the same thread.
  using AllocFn = void *(*)(void *pool, size_t size);
  using DeallocFn = void (*)(void *pool, void *ptr);
  static thread_local inline AllocFn alloc_fn_;
  static thread_local inline DeallocFn dealloc_fn_;
  static thread_local inline void *alloc_pool_;

  static void *operator new(size_t size) {
    if (alloc_fn_)
      return alloc_fn_(alloc_pool_, size);
    return ::operator new(size);
  }

  static void operator delete(void *ptr) noexcept {
    if (dealloc_fn_) {
      dealloc_fn_(alloc_pool_, ptr);
      return;
    }
    ::operator delete(ptr);
  }

  Instruction(const Instruction &) = delete;
  Instruction &operator=(const Instruction &) = delete;
  Instruction(Instruction &&) = delete;
  Instruction &operator=(Instruction &&) = delete;

  /// @brief Direct execute dispatch.  Callers invoke as:
  ///   ``inst->execute(*inst, &ctx)``
  /// Each derived instruction class sets this to a trampoline that calls
  /// its ``execute_impl()`` method.  No virtual dispatch.
  const ExecuteFn execute;

  /// @brief Access the attached dynamic state, or nullptr if none.
  /// @returns Pointer to the dynamic state, or nullptr.
  DynamicInstState *data() { return data_.get(); }
  /// @copydoc data()
  const DynamicInstState *data() const { return data_.get(); }

  /// @brief Typed convenience accessor (unchecked static_cast).
  /// @tparam T Concrete DynamicInstState subclass.
  /// @returns Pointer to the dynamic state cast to @p T.
  template <typename T> T *data_as() {
    assert(dynamic_cast<T *>(data_.get()) != nullptr);
    return static_cast<T *>(data_.get());
  }
  /// @copydoc data_as()
  template <typename T> const T *data_as() const {
    assert(dynamic_cast<const T *>(data_.get()) != nullptr);
    return static_cast<const T *>(data_.get());
  }

  /// @brief Attach dynamic state to this instruction (transfers ownership).
  /// @param[in] d Dynamic state (ownership transferred).
  void set_data(std::unique_ptr<DynamicInstState> d) { data_ = std::move(d); }

protected:
  /// @brief Bind a source operand slot.
  ///
  /// @details Sets both the typed @ref src_operands_ array used by the C++
  /// runtime and the public C ABI mirror in @ref state_.src_operands so
  /// plugins observe the same operand the runtime is dispatching on.
  /// Caller is responsible for updating @c state_.num_src_operands.
  /// @param[in] i  Slot index (must be < ROCJITSU_CODE_INST_MAX_SRC_OPERANDS).
  /// @param[in] op Operand to bind (non-owning; must outlive the instruction).
  void set_src_operand(int i, Operand *op) {
    src_operands_[i] = op;
    state_.src_operands[i] = &op->state_;
  }

  /// @brief Bind a destination operand slot.
  /// @copydetails set_src_operand
  /// @param[in] i  Slot index (must be < ROCJITSU_CODE_INST_MAX_DST_OPERANDS).
  /// @param[in] op Operand to bind (non-owning; must outlive the instruction).
  void set_dst_operand(int i, Operand *op) {
    dst_operands_[i] = op;
    state_.dst_operands[i] = &op->state_;
  }

public:

  /// @brief The instruction's human-readable mnemonic.
  /// @returns Reference to the mnemonic string.
  std::string_view mnemonic() const {
    return state_.mnemonic ? std::string_view(state_.mnemonic) : std::string_view{};
  }

  /// @brief The instruction's total number of operands.
  /// @returns Sum of source and destination operand counts.
  int num_operands() const { return num_src_operands() + num_dst_operands(); }

  /// @brief The instruction's number of source operands.
  /// @returns Source operand count.
  int num_src_operands() const { return static_cast<int>(state_.num_src_operands); }

  /// @brief The instruction's number of destination operands.
  /// @returns Destination operand count.
  int num_dst_operands() const { return static_cast<int>(state_.num_dst_operands); }

  /// @brief Access a source operand by index.
  /// @param i  Operand index (0-based, must be < num_src_operands()).
  /// @returns Pointer to the operand, or nullptr if index out of range.
  [[nodiscard]] const Operand *src_operand(int i) const {
    return (i >= 0 && static_cast<uint32_t>(i) < state_.num_src_operands) ? src_operands_[i]
                                                                          : nullptr;
  }

  /// @brief Access a destination operand by index.
  /// @param i  Operand index (0-based, must be < num_dst_operands()).
  /// @returns Pointer to the operand, or nullptr if index out of range.
  [[nodiscard]] const Operand *dst_operand(int i) const {
    return (i >= 0 && static_cast<uint32_t>(i) < state_.num_dst_operands) ? dst_operands_[i]
                                                                          : nullptr;
  }

  /// @brief Size of the instruction's encoding in bytes.
  /// @returns Encoding size in bytes.
  int size() const { return static_cast<int>(state_.size_bytes); }

  /// @brief Whether this instruction is a direct branch.
  /// @retval true The instruction has BRANCH or COND_BRANCH metadata.
  /// @retval false The instruction is not a direct branch.
  bool is_branch() const { return state_.flags & (BRANCH | COND_BRANCH); }

  /// @brief Whether this instruction is a memory operation.
  /// @retval true The instruction has the MEMORY_OP flag set.
  /// @retval false The instruction is not a memory operation.
  bool is_memory_op() const { return state_.flags & MEMORY_OP; }

  uint64_t flags() const { return state_.flags; }

  bool is_waitcnt() const { return state_.flags & WAITCNT; }

  bool is_barrier() const { return state_.flags & BARRIER; }

  bool is_mfma() const { return state_.flags & MFMA; }

  bool is_accvgpr() const { return state_.flags & ACCVGPR; }

  /// @brief Signed byte offset for a direct branch target.
  ///
  /// @details Generated ISA subclasses override this for direct branches whose
  /// label operand is a signed instruction-count delta. Indirect branches and
  /// non-branches return nullopt.
  [[nodiscard]] virtual std::optional<int64_t> branch_offset_bytes() const { return std::nullopt; }

  /// @brief Add registers implicitly read by this instruction.
  ///
  /// @details Used for encoded fields that affect execution but are not part of
  /// the printed operand list, such as FLAT/GLOBAL `saddr` addressing fields.
  virtual void implicit_uses(RegisterSet & /*uses*/) const {}

  /// @brief Add registers implicitly written by this instruction.
  virtual void implicit_defs(RegisterSet & /*defs*/) const {}

  /// @brief Raw encoding words of this instruction.
  /// @returns Pointer to the encoding words (size()/4 words), or nullptr if not set.
  const uint32_t *raw_encoding() const { return state_.raw_encoding; }

  /// @brief Encoding format ID (the encoding prefix from the machine instruction).
  [[nodiscard]] uint16_t encoding_id() const { return static_cast<uint16_t>(state_.encoding_id); }

  /// @brief Opcode within the encoding format.
  [[nodiscard]] uint16_t opcode() const { return static_cast<uint16_t>(state_.opcode); }

  /// @brief Produce the disassembly string for this instruction.
  ///
  /// @details On first call, generates and caches the disassembly string. Subsequent
  /// calls return the cached string.
  /// @returns Reference to the disassembly string.
  const std::string &disassemble() const {
    if (disassembly_.empty()) {
      disassembly_ = state_.mnemonic ? state_.mnemonic : "";
      bool first = true;
      for (uint32_t i = 0; i < state_.num_dst_operands; ++i) {
        disassembly_ += (first ? " " : ", ");
        disassembly_ += dst_operands_[i]->name();
        first = false;
      }
      for (uint32_t i = 0; i < state_.num_src_operands; ++i) {
        disassembly_ += (first ? " " : ", ");
        disassembly_ += src_operands_[i]->name();
        first = false;
      }
      build_modifiers(disassembly_);
    }
    return disassembly_;
  }

protected:
  /// @brief Instruction's source operands (max 4).
  std::array<Operand *, 4> src_operands_{};
  /// @brief Instruction's destination operands (max 2).
  std::array<Operand *, 2> dst_operands_{};
  /// @brief Append modifier flags to the disassembly string (e.g. " sc0 sc1").
  /// Overridden by memory encoding bases that have flag bits to display.
  /// Default: no modifiers. Called lazily by disassemble().
  virtual void build_modifiers(std::string & /*out*/) const {}
  /// @brief Cached disassembly string.
  mutable std::string disassembly_;
  std::unique_ptr<DynamicInstState> data_;

  /// @brief Plain-data state backing this instruction in the C ABI layout.
  ///
  /// @details Public POD storage so plugins and the C++ runtime share the
  /// same representation. The C struct's @c src_operands / @c dst_operands
  /// pointer arrays are left empty; the C++ runtime uses the typed
  /// @ref src_operands_ / @ref dst_operands_ arrays for virtual dispatch.
  /// Field-level meaning: see @ref rj_code_inst_state_t.
  rj_code_inst_state_t state_{};
};

/// @brief Abstract class that holds static ISA state for a specific instruction instance.
///
/// @details Provides a typed execute() taking the ISA-specific context. Subclasses override
/// this.
/// @tparam Isa ISA traits type providing a Context type alias.
template <typename Isa> class IsaInstruction : public Instruction {
public:
  /// @brief Construct an ISA instruction with the given mnemonic.
  /// @param[in] mnemonic Human-readable mnemonic string.
  IsaInstruction(std::string_view mnemonic, ExecuteFn exec_fn) : Instruction(mnemonic, exec_fn) {}

  /// @brief Helper to create an execute dispatch trampoline for a concrete type.
  ///
  /// The returned function pointer casts the base ``Instruction&`` to the
  /// concrete ``Derived&`` and calls ``execute_impl()`` on it.
  ///
  /// Usage in a constructor init-list:
  /// @code
  ///   AddInst(...) : RType("add", raw, make_exec_fn<AddInst>()) {}
  /// @endcode
  template <typename Derived> static constexpr ExecuteFn make_exec_fn() {
    return [](Instruction &self, void *ctx) {
      static_cast<Derived &>(self).execute_impl(*static_cast<typename Isa::Context *>(ctx));
    };
  }
};

} // namespace rocjitsu

#endif // ROCJITSU_ISA_INSTRUCTION_H_
