// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna4/vexport.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna4 {

ExportVexport::ExportVexport(const MachineInst *inst)
    : Vexport("export", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<ExportVexport>()),
      tgt(128, OperandType::OPR_TGT, reinterpret_cast<const OpEncoding *>(inst)->tgt),
      vsrc0(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc0),
      vsrc1(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1),
      vsrc2(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc2),
      vsrc3(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc3) {
  set_dst_operand(0, &tgt);
  set_src_operand(0, &vsrc0);
  set_src_operand(1, &vsrc1);
  set_src_operand(2, &vsrc2);
  set_src_operand(3, &vsrc3);
  state_.num_src_operands = 4;
  state_.num_dst_operands = 1;
}

void ExportVexport::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Export: no-op in compute simulation.
}

} // namespace rdna4
} // namespace rocjitsu
