name: hipfile-toplevel
run-name: Kicks off several hipFile CI workflows for various platforms

on:
  pull_request:
    types: [opened, synchronize, reopened] # Defaults
    paths:
      - 'projects/hipfile/**'
      - '.github/workflows/hipfile-*.yml'
      - '!**/*.md'
      - '!**/*.rst'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  AIS_CI_Pre-check:
    runs-on: [ubuntu-24.04]
    outputs:
      changed_dockerfile: ${{ steps.ci-flags.outputs.changed_dockerfile }}
      build_ci_image_matrix: ${{ steps.matrices.outputs.build_ci_image_matrix }}
    env:
      # Matrix variables go here in JSON notation.
      # '>-' strips newlines
      SUPPORTED_PLATFORMS: >-
        [
          "rocky",
          "suse",
          "ubuntu"
        ]
      ROCM_VERSIONS: >-
        [
          "7.2.2"
        ]
    steps:
      - name: Fetching code repository...
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          path: rocm-systems
          sparse-checkout: |
            projects/hipfile
            .github/workflows
      - name: Git fetch base ref
        working-directory: rocm-systems
        run: git fetch origin "${GITHUB_BASE_REF}"
      - name: Set CI Flags
        working-directory: rocm-systems/projects/hipfile
        id: ci-flags
        run: |
          echo "changed_dockerfile=$(./util/files-changed.sh "origin/${GITHUB_BASE_REF}" HEAD 'projects/hipfile/util/docker/DOCKERFILE.*')" >> "${GITHUB_OUTPUT}"
      - name: Compute matrix configurations
        id: matrices
        run: |
          build_ci_image_matrix=$(
            jq -c --null-input \
              --argjson supported_platforms "${SUPPORTED_PLATFORMS}" \
              --argjson rocm_versions "${ROCM_VERSIONS}" \
              '{
                supported_platforms: $supported_platforms,
                rocm_versions: $rocm_versions
              }'
          )

          echo "build_ci_image_matrix=${build_ci_image_matrix}" >> ${GITHUB_OUTPUT}

  hipfile-CI:
    needs: [AIS_CI_Pre-check]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.AIS_CI_Pre-check.outputs.build_ci_image_matrix) }}
    uses: ./.github/workflows/hipfile-ci.yml
    with:
      dockerfile_changed: ${{ needs.AIS_CI_Pre-check.outputs.changed_dockerfile == '1' }}
      platform: ${{ matrix.supported_platforms }}
      rocm_version: ${{ matrix.rocm_versions }}
