name: hipfile-toplevel
run-name: Kicks off several hipFile CI workflows for various platforms

on:
  pull_request:
    types: [opened, synchronize, reopened] # Defaults
    paths:
      - 'projects/hipfile/**'
      - '.github/workflows/hipfile-*.yml'
      - '!**/*.md'
      - '!**/*.rst'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  AIS_CI_Pre-check:
    runs-on: [ubuntu-24.04]
    outputs:
      changed_dockerfile: ${{ steps.ci-flags.outputs.changed_dockerfile }}
      build_ci_image_matrix: ${{ steps.matrices.outputs.build_ci_image_matrix }}
      ci_images: ${{ steps.ci-images.outputs.ci_images }}
    env:
      # Matrix variables go here in JSON notation.
      # '>-' strips newlines
      SUPPORTED_PLATFORMS: >-
        [
          "rocky",
          "suse",
          "ubuntu"
        ]
      ROCM_VERSIONS: >-
        [
          "7.2.2"
        ]
    steps:
      - name: Fetching code repository...
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          path: rocm-systems
          sparse-checkout: |
            projects/hipfile
            .github/workflows
      - name: Git fetch base ref
        working-directory: rocm-systems
        run: git fetch origin "${GITHUB_BASE_REF}"
      - name: Set CI Flags
        working-directory: rocm-systems/projects/hipfile
        id: ci-flags
        run: |
          echo "changed_dockerfile=$(./util/files-changed.sh "origin/${GITHUB_BASE_REF}" HEAD 'projects/hipfile/util/docker/DOCKERFILE.*')" >> "${GITHUB_OUTPUT}"
      - name: Compute matrix configurations
        id: matrices
        run: |
          build_ci_image_matrix=$(
            jq -c --null-input \
              --argjson supported_platforms "${SUPPORTED_PLATFORMS}" \
              --argjson rocm_versions "${ROCM_VERSIONS}" \
              '{
                supported_platforms: $supported_platforms,
                rocm_versions: $rocm_versions
              }'
          )

          echo "build_ci_image_matrix=${build_ci_image_matrix}" >> ${GITHUB_OUTPUT}
      - name: Compute CI image names
        id: ci-images
        env:
          REGISTRY_URL: ghcr.io/${{ github.repository_owner }}
          CHANGED_DOCKERFILE: ${{ steps.ci-flags.outputs.changed_dockerfile }}
        run: |
          if [ "${CHANGED_DOCKERFILE}" = "1" ]; then
            # sanitize ref for tag
            tag="$(echo "${GITHUB_REF}" | sed 's|[^a-zA-Z0-9]|-|g')-rocm"
          else
            tag="latest-rocm"
          fi
          # This looks horrible, but is less brittle than Bash
          ci_images=$(
            jq -c -n \
              --arg registry "${REGISTRY_URL}" \
              --arg tag "$tag" \
              --argjson platforms "${SUPPORTED_PLATFORMS}" \
              --argjson versions "${ROCM_VERSIONS}" \
              '
                # Enumerate the complete combination of CI images,
                # then reduce into an object keyed by "platform-version"
                [ 
                  $platforms[] as $p |
                  $versions[] as $v |
                  {platform: $p, version: $v}
                ] | reduce .[] as $combo (
                  {}; . + {
                    ($combo.platform + "-" + $combo.version): (
                      ( $combo
                        | .image_name = ($registry + "/hipfile/ais_ci_" + .platform)
                        | .image      = (.image_name + ":" + $tag + .version)
                        | .cache      = (.image_name + ":latest-rocm" + .version + "-cache")
                      ) | {
                        ci_image:       (.image | ascii_downcase),
                        ci_image_cache: (.cache | ascii_downcase)
                      }
                    )
                  }
                )
              '
          )
          echo "List of CI Images: "
          echo "${ci_images}" | jq .
          echo "ci_images=${ci_images}" >> "${GITHUB_OUTPUT}"

  build_AIS_CI_image:
    if: ${{ needs.AIS_CI_Pre-check.outputs.changed_dockerfile == '1' }}
    needs: AIS_CI_Pre-check
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.AIS_CI_Pre-check.outputs.build_ci_image_matrix) }}
    uses: ./.github/workflows/hipfile-image-build.yml
    with:
      ci_image_name: ${{ fromJSON(needs.AIS_CI_Pre-check.outputs.ci_images)[format('{0}-{1}', matrix.supported_platforms, matrix.rocm_versions)].ci_image }}
      ci_image_cache: ${{ fromJSON(needs.AIS_CI_Pre-check.outputs.ci_images)[format('{0}-{1}', matrix.supported_platforms, matrix.rocm_versions)].ci_image_cache }}
      platform: ${{ matrix.supported_platforms }}
      rocm_version: ${{ matrix.rocm_versions }}

  # Due to GHA matrix limitations, we cannot inspect the result of individual jobs
  # in the matrix. To avoid confusing errors, our only option is that if a single
  # build fails, the entire workflow must stop. Which is rather unfortunate.

  hipfile-CI:
    if: >-
      ${{
        !cancelled() && (
          needs.build_AIS_CI_image.result == 'success' ||
          needs.build_AIS_CI_image.result == 'skipped'
        )
      }}
    needs: [AIS_CI_Pre-check, build_AIS_CI_image]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.AIS_CI_Pre-check.outputs.build_ci_image_matrix) }}
    uses: ./.github/workflows/hipfile-ci.yml
    with:
      ci_image: ${{ fromJSON(needs.AIS_CI_Pre-check.outputs.ci_images)[format('{0}-{1}', matrix.supported_platforms, matrix.rocm_versions)].ci_image }}
      platform: ${{ matrix.supported_platforms }}
      rocm_version: ${{ matrix.rocm_versions }}
